"""empty message

Revision ID: 0314fcdf750f
Revises: 188c3fde1712
Create Date: 2026-01-16 00:41:01.278025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0314fcdf750f'
down_revision = '188c3fde1712'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
