"""Add Calculated Dates to Service Records

Revision ID: 0950807d9475
Revises: 
Create Date: 2025-01-22 16:54:13.356481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0950807d9475'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('checkup_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('litter_guard1_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('litter_guard2_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('feed_up_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('action_date', sa.Date(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_column('action_date')
        batch_op.drop_column('due_date')
        batch_op.drop_column('feed_up_date')
        batch_op.drop_column('litter_guard2_date')
        batch_op.drop_column('litter_guard1_date')
        batch_op.drop_column('checkup_date')

    # ### end Alembic commands ###
