"""changed invoice number nullable to false

Revision ID: 1331dd22e8c4
Revises: 3a3a11cd5aaf
Create Date: 2025-04-30 08:51:05.480484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1331dd22e8c4'
down_revision = '3a3a11cd5aaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.alter_column('invoice_number',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
