"""empty message

Revision ID: 188c3fde1712
Revises: 776dd9841208
Create Date: 2026-01-15 23:00:28.065148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188c3fde1712'
down_revision = '776dd9841208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.alter_column('DOB',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###
