"""added a new column to the expenses

Revision ID: 3a3a11cd5aaf
Revises: 3d3fcf3f6325
Create Date: 2025-04-30 08:32:11.639450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3a11cd5aaf'
down_revision = '3d3fcf3f6325'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
