"""empty message

Revision ID: 3c8800ec07c6
Revises: 4a6ec2bad21e
Create Date: 2026-01-30 07:18:55.925386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8800ec07c6'
down_revision = '4a6ec2bad21e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_country_iso', sa.String(length=5), nullable=True))
        batch_op.alter_column('phone_country_code',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phone_country_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               existing_nullable=True)
        batch_op.drop_column('phone_country_iso')

    # ### end Alembic commands ###
