"""empty message

Revision ID: 4a6ec2bad21e
Revises: 
Create Date: 2026-01-29 21:30:19.453267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6ec2bad21e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('system_setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('verification_token', sa.String(length=200), nullable=True),
    sa.Column('verification_expiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('password_reset_token', sa.String(length=128), nullable=True),
    sa.Column('password_reset_expiry', sa.DateTime(), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('profile_pic', sa.String(length=512), nullable=True),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('phone_country_code', sa.String(length=5), nullable=True),
    sa.Column('farm_name', sa.String(length=100), nullable=True),
    sa.Column('farm_address', sa.Text(), nullable=True),
    sa.Column('farm_city', sa.String(length=50), nullable=True),
    sa.Column('farm_state', sa.String(length=50), nullable=True),
    sa.Column('farm_country', sa.String(length=50), nullable=True),
    sa.Column('farm_postal_code', sa.String(length=20), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('profile_picture', sa.String(length=255), nullable=True),
    sa.Column('farm_logo', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notify_email', sa.Boolean(), nullable=True),
    sa.Column('notify_sms', sa.Boolean(), nullable=True),
    sa.Column('notify_push', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('boars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BoarId', sa.String(length=20), nullable=False),
    sa.Column('Breed', sa.String(length=50), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('BoarId', 'user_id', name='uix_boarid_userid')
    )
    with op.batch_alter_table('boars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boars_BoarId'), ['BoarId'], unique=False)
        batch_op.create_index(batch_op.f('ix_boars_Breed'), ['Breed'], unique=False)

    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'invoice_number', name='uix_user_receipt')
    )
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('num_of_pigs', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=False),
    sa.Column('average_weight', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number', 'user_id', name='uix_invoiceid_userid')
    )
    op.create_table('page_view',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser', sa.String(length=50), nullable=True),
    sa.Column('response_time', sa.Float(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_view_path'), ['path'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_view_timestamp'), ['timestamp'], unique=False)

    op.create_table('sows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sowID', sa.String(length=20), nullable=False),
    sa.Column('Breed', sa.String(length=50), server_default='UNKNOWN', nullable=False),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sowID', 'user_id', name='uix_sowid_userid')
    )
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sows_Breed'), ['Breed'], unique=False)
        batch_op.create_index(batch_op.f('ix_sows_sowID'), ['sowID'], unique=False)

    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sow_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=True),
    sa.Column('boar_used', sa.String(length=50), nullable=False),
    sa.Column('checkup_date', sa.Date(), nullable=True),
    sa.Column('litter_guard1_date', sa.Date(), nullable=True),
    sa.Column('litter_guard2_date', sa.Date(), nullable=True),
    sa.Column('feed_up_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('action_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sow_id', 'service_date', name='uix_sow_service_date')
    )
    op.create_table('litter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sow_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('farrowDate', sa.Date(), nullable=False),
    sa.Column('totalBorn', sa.Integer(), nullable=False),
    sa.Column('bornAlive', sa.Integer(), nullable=False),
    sa.Column('stillBorn', sa.Integer(), nullable=True),
    sa.Column('mummified', sa.Integer(), nullable=True),
    sa.Column('averageWeight', sa.Float(), nullable=True),
    sa.Column('weights', sa.String(length=500), nullable=True),
    sa.Column('iron_injection_date', sa.Date(), nullable=True),
    sa.Column('teeth_clipping_date', sa.Date(), nullable=True),
    sa.Column('tail_docking_date', sa.Date(), nullable=True),
    sa.Column('castration_date', sa.Date(), nullable=True),
    sa.Column('wean_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['service_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sow_id'], ['sows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('litter_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('management_type', sa.String(length=50), nullable=False),
    sa.Column('other_litter_id', sa.String(length=50), nullable=True),
    sa.Column('piglets_moved', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortality_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('number_died', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=50), nullable=False),
    sa.Column('other_cause', sa.String(length=200), nullable=True),
    sa.Column('age_at_death', sa.Integer(), nullable=True),
    sa.Column('weight_at_death', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('number_sold', sa.Integer(), nullable=False),
    sa.Column('average_weight', sa.Float(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('buyer_name', sa.String(length=100), nullable=True),
    sa.Column('buyer_contact', sa.String(length=100), nullable=True),
    sa.Column('sale_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vaccine_type', sa.String(length=100), nullable=False),
    sa.Column('other_vaccine_name', sa.String(length=100), nullable=True),
    sa.Column('piglets_vaccinated', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.Float(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('administered_by', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_type', sa.String(length=20), nullable=True),
    sa.Column('piglets_weighed', sa.Integer(), nullable=True),
    sa.Column('average_weight', sa.Float(), nullable=False),
    sa.Column('individual_weights', sa.Text(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weight_record')
    op.drop_table('vaccination_record')
    op.drop_table('sale_record')
    op.drop_table('mortality_record')
    op.drop_table('litter_management')
    op.drop_table('litter')
    op.drop_table('service_records')
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sows_sowID'))
        batch_op.drop_index(batch_op.f('ix_sows_Breed'))

    op.drop_table('sows')
    with op.batch_alter_table('page_view', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_view_timestamp'))
        batch_op.drop_index(batch_op.f('ix_page_view_path'))

    op.drop_table('page_view')
    op.drop_table('invoice')
    op.drop_table('expense')
    with op.batch_alter_table('boars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boars_Breed'))
        batch_op.drop_index(batch_op.f('ix_boars_BoarId'))

    op.drop_table('boars')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activity_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_activity_log_action'))

    op.drop_table('activity_log')
    op.drop_table('user')
    op.drop_table('system_setting')
    op.drop_table('admin_user')
    # ### end Alembic commands ###
