"""trying to add a new nullable column with a database that has data

Revision ID: 62c9be3de755
Revises: bd597cc6bb0f
Create Date: 2025-12-27 17:16:35.940046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c9be3de755'
down_revision = 'bd597cc6bb0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mummified', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weights', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tail_docking_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('farrowDate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('stillBorn',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('iron_injection_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('teeth_clipping_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('castration_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('wean_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'service_records', ['service_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tail_dorking_date')
        batch_op.drop_column('service_record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_record_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tail_dorking_date', sa.DATE(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'service_records', ['service_record_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('wean_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('castration_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('teeth_clipping_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('iron_injection_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('stillBorn',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('farrowDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('tail_docking_date')
        batch_op.drop_column('stage')
        batch_op.drop_column('weights')
        batch_op.drop_column('mummified')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###
