"""empty message

Revision ID: 7022f0ea74b8
Revises: da9d3186095a
Create Date: 2025-04-30 09:42:32.011809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7022f0ea74b8'
down_revision = 'da9d3186095a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_column('receipt_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('receipt_number', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
