"""Add verification_expiry column in user

Revision ID: 75741ba38d69
Revises: 282c154c05ad
Create Date: 2025-08-13 23:45:47.335250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75741ba38d69'
down_revision = '282c154c05ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verification_expiry', sa.DateTime(), nullable=True))
        batch_op.alter_column('verification_token',
               existing_type=sa.TEXT(),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('verification_token',
               existing_type=sa.String(length=128),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('verification_expiry')

    # ### end Alembic commands ###
