"""Add Breed column to sows table

Revision ID: 81ee45db97e3
Revises: c020c96066d4
Create Date: 2025-04-01 13:43:24.909011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ee45db97e3'
down_revision = 'c020c96066d4'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     with op.batch_alter_table('sows', schema=None) as batch_op:
#         batch_op.add_column(sa.Column('Breed', sa.String(length=50), nullable=False))
#         batch_op.create_index(batch_op.f('ix_sows_Breed'), ['Breed'], unique=True)

    # ### end Alembic commands ###

def upgrade():
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('Breed', sa.String(length=50), nullable=False, server_default='UNKNOWN')
        )
        batch_op.create_index(batch_op.f('ix_sows_Breed'), ['Breed'], unique=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sows_Breed'))
        batch_op.drop_column('Breed')

    # ### end Alembic commands ###
