"""database change

Revision ID: bd597cc6bb0f
Revises: 75741ba38d69
Create Date: 2025-12-27 16:55:51.293929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd597cc6bb0f'
down_revision = '75741ba38d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('litter_management',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('management_type', sa.String(length=50), nullable=False),
    sa.Column('other_litter_id', sa.String(length=50), nullable=True),
    sa.Column('piglets_moved', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mortality_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('number_died', sa.Integer(), nullable=False),
    sa.Column('cause', sa.String(length=50), nullable=False),
    sa.Column('other_cause', sa.String(length=200), nullable=True),
    sa.Column('age_at_death', sa.Integer(), nullable=True),
    sa.Column('weight_at_death', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('number_sold', sa.Integer(), nullable=False),
    sa.Column('average_weight', sa.Float(), nullable=False),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('price_per_kg', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('buyer_name', sa.String(length=100), nullable=True),
    sa.Column('buyer_contact', sa.String(length=100), nullable=True),
    sa.Column('sale_type', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vaccination_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('vaccine_type', sa.String(length=100), nullable=False),
    sa.Column('other_vaccine_name', sa.String(length=100), nullable=True),
    sa.Column('piglets_vaccinated', sa.Integer(), nullable=False),
    sa.Column('dosage', sa.Float(), nullable=True),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('administered_by', sa.String(length=100), nullable=True),
    sa.Column('batch_number', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weight_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('litter_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_type', sa.String(length=20), nullable=True),
    sa.Column('piglets_weighed', sa.Integer(), nullable=True),
    sa.Column('average_weight', sa.Float(), nullable=False),
    sa.Column('individual_weights', sa.Text(), nullable=True),
    sa.Column('total_weight', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['litter_id'], ['litter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_user')
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('mummified', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weights', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tail_docking_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('farrowDate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('stillBorn',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('iron_injection_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('teeth_clipping_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('castration_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('wean_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('tail_dorking_date')
        batch_op.drop_column('service_record_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_record_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tail_dorking_date', sa.DATE(), nullable=False))
        batch_op.alter_column('wean_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('castration_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('teeth_clipping_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('iron_injection_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('stillBorn',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('farrowDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('tail_docking_date')
        batch_op.drop_column('stage')
        batch_op.drop_column('weights')
        batch_op.drop_column('mummified')
        batch_op.drop_column('service_id')

    op.create_table('_alembic_tmp_user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=150), nullable=False),
    sa.Column('email', sa.VARCHAR(length=200), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), nullable=True),
    sa.Column('google_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('profile_pic', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('0'), nullable=True),
    sa.Column('verification_token', sa.VARCHAR(length=128), nullable=True),
    sa.Column('verification_expiry', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_id'),
    sa.UniqueConstraint('username')
    )
    op.drop_table('weight_record')
    op.drop_table('vaccination_record')
    op.drop_table('sale_record')
    op.drop_table('mortality_record')
    op.drop_table('litter_management')
    # ### end Alembic commands ###
