"""Added boars table

Revision ID: c020c96066d4
Revises: 0950807d9475
Create Date: 2025-02-10 10:55:26.795111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c020c96066d4'
down_revision = '0950807d9475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('BoarId', sa.String(length=20), nullable=False),
    sa.Column('DOB', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boars_BoarId'), ['BoarId'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('boars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boars_BoarId'))

    op.drop_table('boars')
    # ### end Alembic commands ###
