"""empty message

Revision ID: c7623df13332
Revises: 62c9be3de755
Create Date: 2025-12-27 17:19:05.005142

"""
from alembic import op
import sqlalchemy as sa


naming_convention = {
    "ix": 'ix_%(column_0_label)s',
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s"
}

# revision identifiers, used by Alembic.
revision = 'c7623df13332'
down_revision = '62c9be3de755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.Integer(), nullable=True))  # Temporarily nullable if data exists
        batch_op.add_column(sa.Column('mummified', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weights', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('stage', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('tail_docking_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('farrowDate',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('stillBorn',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('iron_injection_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('teeth_clipping_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('castration_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('wean_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_constraint('fk_litter_service_record_id_service_records', type_='foreignkey')
        batch_op.create_foreign_key('fk_litter_service_id_service_records', 'service_records', ['service_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tail_dorking_date')
        batch_op.drop_column('service_record_id')


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('litter', schema=None, naming_convention=naming_convention) as batch_op:
        batch_op.add_column(sa.Column('service_record_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('tail_dorking_date', sa.DATE(), nullable=True))  # Adjust nullable based on original
        batch_op.drop_constraint('fk_litter_service_id_service_records', type_='foreignkey')
        batch_op.create_foreign_key('fk_litter_service_record_id_service_records', 'service_records', ['service_record_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('wean_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('castration_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('teeth_clipping_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('iron_injection_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('stillBorn',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('farrowDate',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('created_at')
        batch_op.drop_column('tail_docking_date')
        batch_op.drop_column('stage')
        batch_op.drop_column('weights')
        batch_op.drop_column('mummified')
        batch_op.drop_column('service_id')


    # ### end Alembic commands ###
