"""empty message

Revision ID: da9d3186095a
Revises: 1331dd22e8c4
Create Date: 2025-04-30 09:42:09.993890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da9d3186095a'
down_revision = '1331dd22e8c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_receipt', type_='unique')
        batch_op.create_unique_constraint('uix_user_receipt', ['user_id', 'invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expense', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_receipt', type_='unique')
        batch_op.create_unique_constraint('uix_user_receipt', ['user_id', 'receipt_number'])

    # ### end Alembic commands ###
